language: generic
sudo: required
services:
    - docker

before_install:
    - docker build -t gstein17/roboscape-simulator .

script:
    - docker run -e CI=true gstein17/roboscape-simulator npm run test -- --coverage
