name: Build, test, publish

on:
  push:
    tags: 'v*'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c Release
    - name: Test
      run: dotnet test --no-build --verbosity normal --filter "Category!=LongRunning"
    - name: Build
      run: dotnet publish --no-restore -c Release
    - name: docker build
      run: docker build -t gstein17/roboscapeonlineserver-dotnet .
    - name: docker login
      run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    - name: docker push
      run: docker push gstein17/roboscapeonlineserver-dotnet
