on:
  push:
    branches:
      - master
name: npm build, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: npm install
        run: npm ci --no-save
      - name: npm test
        run: npm test
      - name: codecov
        run: npx jest --coverage && npx codecov -t ${{ secrets.CODECOV_TOKEN }}
