on:
  push:
    branches:
      - master
name: npm build, test and publish
jobs:
  build-and-publish:
    name: build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Setup Node.js for use with actions
        uses: actions/setup-node@v1.1.0
        with:
          version: 12.x
      - name: npm install
        run: npm ci --no-save
      - name: npm test
        run: npm test
      - name: docker build
        run: docker build -t gstein17/roboscape-simulator .
      - name: docker login
        run: docker login --username $DOCKER_USERNAME --password $DOCKER_PASSWORD
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      - name: docker push
        run: docker push gstein17/roboscape-simulator
      - name: codecov
        run: npx jest && npx codecov -t :${{ secrets.CODECOV_TOKEN }}
